algoritmo "Cálculo de média"
var
   primeiroNumero, segundoNumero, media: real
inicio
      escreval("--------------")
      escreval("     Média    ")
      escreval("--------------")
      escreva("Informe o primeiro número: ")
      leia(primeiroNumero)
      escreva("Informe o primeiro número: ")
      leia(segundoNumero)
      media <- (primeiroNumero + segundoNumero) / 2
      escreva("A média é", media)
fimalgoritmo